#!/usr/bin/env python3
"""
Debug script to test summarization functionality.

This script helps diagnose why summaries aren't appearing in generated notes.
"""

import sys
import os
sys.path.insert(0, os.path.abspath(os.path.dirname(os.path.dirname(__file__))))

from src.settings import settings
from src.summarization import get_summarization_tags, check_summarization_required
from src.decision_logic import DecisionLogic, ClassificationResult, ClassificationStatus
from src.llm_client import LLMResponse

def test_summarization_config():
    """Test if summarization is configured correctly."""
    print("=" * 60)
    print("SUMMARIZATION CONFIGURATION TEST")
    print("=" * 60)
    
    # Initialize settings
    settings.initialize()
    
    # Check summarization tags
    summarization_tags = get_summarization_tags()
    print(f"\n1. Summarization tags from config: {summarization_tags}")
    
    if not summarization_tags:
        print("   [ERROR] No summarization tags configured!")
        print("   → Add 'summarization_tags: [\"important\"]' to config.yaml")
        return False
    else:
        print("   [OK] Summarization tags found")
    
    # Check prompt path
    try:
        paths_config = settings._config.paths
        prompt_path = getattr(paths_config, 'summarization_prompt_path', None)
        print(f"\n2. Summarization prompt path: {prompt_path}")
        
        if prompt_path and os.path.exists(prompt_path):
            print(f"   [OK] Prompt file exists: {prompt_path}")
        else:
            print(f"   [ERROR] Prompt file not found: {prompt_path}")
            return False
    except Exception as e:
        print(f"   [ERROR] accessing prompt path: {e}")
        return False
    
    # Test tag matching
    print(f"\n3. Testing tag matching:")
    test_tags = ['email', 'important']
    print(f"   Test email tags: {test_tags}")
    print(f"   Config tags: {summarization_tags}")
    
    from src.summarization import should_summarize_email
    should_summarize = should_summarize_email(test_tags, summarization_tags)
    print(f"   Should summarize: {should_summarize}")
    
    if not should_summarize:
        print("   [ERROR] Tags don't match!")
        print(f"   → Check that 'important' is in both email tags and summarization_tags")
        return False
    else:
        print("   [OK] Tag matching works")
    
    # Test check_summarization_required
    print(f"\n4. Testing check_summarization_required:")
    test_email = {'tags': test_tags}
    result = check_summarization_required(test_email)
    print(f"   Result: {result}")
    
    if result.get('summarize'):
        print("   [OK] Summarization check passes")
    else:
        print(f"   ❌ Summarization check failed: {result.get('reason')}")
        return False
    
    print("\n" + "=" * 60)
    print("[OK] All configuration checks passed!")
    print("=" * 60)
    return True


def test_classification_result_tags():
    """Test what tags are generated by classification result."""
    print("\n" + "=" * 60)
    print("CLASSIFICATION RESULT TAGS TEST")
    print("=" * 60)
    
    # Create a test classification result that should be important
    classification_result = ClassificationResult(
        is_important=True,
        is_spam=False,
        importance_score=9,
        spam_score=2,
        confidence=0.9,
        status=ClassificationStatus.SUCCESS,
        raw_scores={'spam_score': 2, 'importance_score': 9},
        metadata={}
    )
    
    # Get tags from frontmatter dict
    frontmatter = classification_result.to_frontmatter_dict()
    tags = frontmatter.get('tags', [])
    
    print(f"\nClassification result tags: {tags}")
    print(f"Is important: {classification_result.is_important}")
    print(f"Importance score: {classification_result.importance_score}")
    
    # Check if 'important' is in tags
    if 'important' in tags:
        print("   [OK] 'important' tag is present")
    else:
        print("   [ERROR] 'important' tag is missing!")
        print(f"   → Tags generated: {tags}")
        return False
    
    # Test with summarization check
    print(f"\nTesting with summarization check:")
    test_email = {'tags': tags}
    result = check_summarization_required(test_email)
    print(f"   Result: {result}")
    
    if result.get('summarize'):
        print("   [OK] Would trigger summarization")
    else:
        print(f"   [ERROR] Would NOT trigger summarization: {result.get('reason')}")
        return False
    
    return True


if __name__ == '__main__':
    print("\nSummarization Debug Test\n")
    
    config_ok = test_summarization_config()
    if not config_ok:
        print("\n[ERROR] Configuration test failed. Fix issues above.")
        sys.exit(1)
    
    tags_ok = test_classification_result_tags()
    if not tags_ok:
        print("\n[ERROR] Tag matching test failed. Check tag generation.")
        sys.exit(1)
    
    print("\n[OK] All tests passed! Summarization should work.")
    print("\nNext steps:")
    print("1. Process an email with importance_score >= 8")
    print("2. Check logs for 'Summarization required' messages")
    print("3. Check generated note files for summary callouts")
